// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WineShop.Data;

#nullable disable

namespace WineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WineShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int>("Quantity").HasColumnType("integer");
                    b.Property<string>("SessionId").IsRequired().HasColumnType("text");
                    b.Property<int>("WineId").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("WineId");
                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("WineShop.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Alcohol").HasColumnType("decimal(4,1)");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<string>("GrapeType").IsRequired().HasColumnType("text");
                    b.Property<string>("ImageUrl").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<decimal>("Price").HasColumnType("decimal(10,2)");
                    b.Property<string>("ProducerEmail").HasColumnType("text");
                    b.Property<string>("ProducerPhone").HasColumnType("text");
                    b.Property<string>("SearchVector").HasColumnType("text");
                    b.Property<string>("WineType").IsRequired().HasColumnType("text");
                    b.Property<int>("Year").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineShop.Models.CartItem", b =>
                {
                    b.HasOne("WineShop.Models.Wine", "Wine")
                        .WithMany()
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Wine");
                });
#pragma warning restore 612, 618
        }
    }
}
